Vagrant::Config.run do |config|
	config.vm.box = "lucid32"

	#config.vm.boot_mode = :gui

	config.vm.provision :puppet do |puppet|
		puppet.manifests_path = "manifests"
		puppet.module_path = "modules"
		puppet.manifest_file = "default.pp"
	end
  
	config.vm.forward_port 80, 4567
  
end
